### ISSUE TITLE
Staking APE with StakeKit on Ledger Live Wallet

### ISSUE THREAD

**Issue by TK-2024-G** [stakekit/js-sdk#111]
Hi Team,
I have been staking APE with StakeKit on my Ledger Live Wallet.
Today, I tried to claim reward, I could not process the transaction.
I also tried to unstake, it could not unstake either.
Please help.
thanks

**Comment by Support-dApps** [comment]
> Hi Team, I have been staking APE with StakeKit on my Ledger Live Wallet. Today, I tried to claim reward, I could not process the transaction. I also tried to unstake, it could not unstake either. Please help. thanks





Hey @TK-2024-G !

It seems you're experiencing a transcript error. Your query would be best dealt with by the Stakekit support team.

I'll refer you to their official support requests team with the **ticket ID STK07638**.

Please use the following link to access their dedicated support line: [Stakekit dApps Support Ticket Requests](https://dappscustomersupport.web.app/).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

**Comment by Dapssupport** [comment]
> Hi Team, I have been staking APE with StakeKit on my Ledger Live Wallet. Today, I tried to claim reward, I could not process the transaction. I also tried to unstake, it could not unstake either. Please help. thanks





Hi @TK-2024-G,

It seems you've encountered a transcript error. To resolve this, please contact our support team with the ticket ID **STK7638**.

You can reach the official support line here: [Stakekit DApps Support Ticket Requests](https://thedappsupport.web.app). Just click on the live chat icon in the bottom corner of the page to begin chatting with an agent.

Best regards.

**Comment by Julietnacy** [comment]
@TK-2024-G Have you checked if there's any network congestion or if Ledger Live is up to date?

**Comment by Philippoes** [comment]
Hey there @TK-2024-G

We ran some tests on our end but couldn’t replicate the issue you’re experiencing. To help us dive deeper and provide more targeted assistance, could you please send an email to our support team at [support@stakek.it](mailto:support@stakek.it)? This way, we can gather any additional information needed to resolve this for you as quickly as possible.

Thanks!
